#!/usr/bin/env bash
# Your Bash script must accept 2 arguments:Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

print_dns_info () {

	local domain="$1"
	local subdomain="$2"

	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
		for sub in "${subdomains[@]}"; do
			dns_info=$(dig  $sub.$domain | grep -A1 'ANSWER SECTION:')
			record_type=$(echo "$dns_info" | awk '{print $4}')
			destination=$(echo "$dns_info" | awk '{print $5}')
			echo "The subdomain $sub.$domain is a $record_type record and points to $destination"
	done
	else
		dns_info=$(dig  $subdomain.$domain | grep -A1 'ANSWER SECTION:')
		record_type=$(echo "$dns_info" | awk '{print $4}')
		destination=$(echo "$dns_info" | awk '{print $5}')
		echo "The subdomain $subdomain.$domain is a $record_type record and points to $destination"
	fi
}
domain=$1
subdomain=$2
print_dns_info "$domain" "$subdomain"
