#!/usr/bin/env bash
# This script transfers a file from our client to a server

if [ $# -lt 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else

	PATH_TO_FILE=$1
	IP=$2
	USERNAME=$3
	PATH_TO_SSH_KEY=$4

	scp -o StricthostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi



