#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  eyasu-frontend
        bind *:80
        mode http
        default_backend eyasu-backend
backend eyasu-backend
        balance roundrobin
        server 512233-web-01 54.158.203.28:80 check
        server 512233-web-02 52.91.156.191:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg


echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
