#!/usr/bin/env bash


file_path="/var/run/my_process.pid"

case "$1" in
	start)

		./manage_my_process &
		echo $! > $file_path
		echo "manage_my_process started"
		;;
	stop)
		kill $(cat $file_path)
		rm $file_path
		echo "manage_my_process stopped"
		;;
	restart)
		kill $(cat $file_path)
		rm $file_path
		./manage_my_process &
		echo $! > $file_path
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac




