#!/usr/bin/env bash
#This script displays the content of /etc/passwd


exec 3< /etc/passwd

while IFS=: read -u 3 -r  USERNAME PASSWORD USERID GROUPID USERINFO HOMEDIR COMMANDSHELL ; do
	echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOMEDIR and rides $COMMANDSHELL. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERINFO"
done
